### ISSUE TITLE
infra destroy doesn't seem to work

### ISSUE THREAD

**Issue by alexakarpov** [poanetwork/poa-explorer-infra#33]
So after creating the terraform.tfvars file, which allowed to skip all the prompts, I got past the previous problem, the one which is mentioned in the README:

> The installer will prompt during its initial run to ask if you want to migrate the Terraform state to S3, this is a necessary step

That immediatey fails. But before I get into that, the second issue, which I believe is more serious, manifested itself:

> ➜  poa-explorer-infra git:(master) ✗ ./bin/infra destroy
> Error: Error loading modules: module stack: not found, may need to run 'terraform init'

As now but the S3 bucket and the DinamoDB table are being successfully created, the cleanup is longer. Those two, and the local state:

> akamac.home ➜  poa-explorer-infra git:(master) ✗ rm -rf .terraform 
> akamac.home ➜  poa-explorer-infra git:(master) ✗ rm -rf terraform.tfstate.d 

destroy was supposed to take care of all 4, correct?

Now, the failure to migrate. The bucket does exist; I was able to copy the file there with aws s3 cp <s3_url> <local_file> - presumably nothing should be in the way of the 'provision' script, right?

The dialog is being very polite and explains everything that needs to happen. "Local" backend to the S3 one, which was just created. However,

>   Enter a value: yes
> 
> Error migrating the workspace "base" from the previous "local" backend to the newly
> configured "s3" backend:
>     Error loading state:
>     failed to lock s3 state: 2 error(s) occurred:
> 
> * ResourceNotFoundException: Requested resource not found
> 	status code: 400, request id: F06O603P6T3AJPDNLBPAHQS60FVV4KQNSO5AEMVJF66Q9ASUAAJG
> * ResourceNotFoundException: Requested resource not found
> 	status code: 400, request id: RATGBBS4B7FP1CJUNVCI4TQSMFVV4KQNSO5AEMVJF6

Very strange. Two errors, not one. One for a local, and one for remote? Neither is found? Well, "locally" I wasn't asked to create any state manually, so I assume the script and Terraform did everything; and remote bucket was created just fine..

**Comment by bitwalker** [comment]
Part of the problem here is the gymnastics required to push the remote state for Terraform to S3, if something interrupts the bootstrapping process, then the `destroy` command will not work, as you've seen here. The two errors it is complaining about are almost certainly the resources required for the state locking feature (the DynamoDB table, and S3 bucket for the locks, there is also an S3 bucket for the state itself, but that is not the issue in this specific error report). This can occur if the bootstrapping fails before creating those resources for some reason.

Your best bet is to start fresh, there is a hidden command `destroy_setup`, which will blow away the DynamoDB table and two S3 buckets, as well as the local Terraform state. I would run that, make sure the local state is gone, and then re-run `provision` now that you have the `terraform.tfvars` file created.

**Comment by alexakarpov** [comment]
Thanks @bitwalker, I will try this as soon as I get back to my machine. Interestingly enough, the bootstrap process didn't report any problems, but perhaps I didn't know where to look )

**Comment by alexakarpov** [comment]
thanks for that tip re: the hidden command; it cleared the way and allowed to find the typo that was preventing the successful initialization of the whole setup. So now that I got here, I'm being instructed to report another issue - as if this new failure is actually expected to happen! =)
