### ISSUE TITLE
mix ecto.drop is not dropping the database during build

### ISSUE THREAD

**Issue by acravenho** [poanetwork/poa-explorer-infra#35]
I recently attempted to drop the database by adding `mix ecto.drop` to `bin/deployment/migrate` but the database did not drop. Is there something else I should be adding to this file?

**Comment by bitwalker** [comment]
Was there any error output? I would assume this is how we should be dropping the database, but perhaps it may be a better question for @KronicDeth or @alexgaribay since I'm not as familiar with the details of the application itself

**Comment by acravenho** [comment]
There was no error given during the build. Everything continued on as normal but the database never dropped. I'm wondering if it didn't have the right permissions to drop the db.

**Comment by KronicDeth** [comment]
RDS PostgreSQL permissions work the same as normal postgres in that you need either `CREATEDB` or to be the `owner` (in postgres, not in RDS/AWS permissions) of the database to `DROP` it.  Of course, to drop and recreate you need `CREATEDB`, so you'll need to be the owner to DROP (or some level of admin that can drop databases you don't own) and then also have `CREATEDB` permissions.

**Comment by bitwalker** [comment]
The script is run with `set -e` at the top, so if a command exits non-zero, it _should_ fail the entire script as a result. There are some caveats with that in Bash, but I would guess the command actually succeeded, but perhaps didn't do what we think that command does. i think you need to add `--force` as an argument, because otherwise it expects user input for confirmation, at least based on the docs.

**Comment by bitwalker** [comment]
The user these scripts run with has sufficient permissions to create databases, and as far as I'm aware, permission to drop them as well.

**Comment by acravenho** [comment]
I'll give it a try with `--force`.

**Comment by acravenho** [comment]
Here is the error that I'm receiving using `mix ecto.drop --force`

```Log TailLifecycleEvent - ApplicationStart
Script - bin/deployment/migrate
[stdout]==> ethereum_jsonrpc
[stdout]Compiling 15 files (.ex)
[stdout]Generated ethereum_jsonrpc app
[stdout]==> explorer
[stdout]Compiling 47 files (.ex)
[stdout]Generated explorer app
[stdout]==> explorer_web
[stdout]Compiling 47 files (.ex)
[stdout]Generated explorer_web app
[stderr]** (Mix) The database for Explorer.Repo couldn't be dropped: ERROR 55006 (object_in_use): database "sokol" is being accessed by other users
[stderr]
[stderr]There are 10 other sessions using the database.```

**Comment by acravenho** [comment]
@bitwalker Any luck finding a resolution to the above issue?

**Comment by acravenho** [comment]
@bitwalker The only way I'm finding a solution to this is by destroying this build and starting an entirely new build.

**Comment by bitwalker** [comment]
Hmm, I think this is a rare case where you need to connect as a superuser directly, drop all other connections to the database forcibly, then dropping the database by hand, letting the new version run the schema migrations and seeds from scratch. I don't think there is a way for us to have Ecto kick users during a drop - it seems to assume that the drop will be run by the only connected session. I haven't dug in further, but my recommendation would be to treat this as a one-off manual job, rather than trying to deploy this as part of a deployment lifecycle event. If it truly needs to be automated, then we probably need to run a shell command with `psql` to connect as superuser, drop other connections, and drop the database, rather than using `mix ecto.drop`.

**Comment by acravenho** [comment]
Thanks, @bitwalker. I think you're right. I don't see many times that we'll need to drop in the future. I will do it manually for now 👍

**Comment by KronicDeth** [comment]
@acravenho this is my go-to answer for how to kick clients in Postgres https://stackoverflow.com/a/5408501/470451

**Comment by acravenho** [comment]
Bookmarked, thank you 👍

**Comment by bikashdas** [comment]
Is this issue resolved? since i am still unable to drop db despite using `--force`. And it is rather frequent
